export const EVALUATION_RATING_CREATE_REQUEST =
  "EVALUATION_RATING_CREATE_REQUEST";
export const EVALUATION_RATING_CREATE_SUCCESS =
  "EVALUATION_RATING_CREATE_SUCCESS";
export const EVALUATION_RATING_CREATE_FAIL = "EVALUATION_RATING_CREATE_FAIL";
export const EVALUATION_RATING_CREATE_RESET = "EVALUATION_RATING_CREATE_RESET";

export const EVALUATION_RATING_LIST_REQUEST = "EVALUATION_RATING_LIST_REQUEST";
export const EVALUATION_RATING_LIST_SUCCESS = "EVALUATION_RATING_LIST_SUCCESS";
export const EVALUATION_RATING_LIST_FAIL = "EVALUATION_RATING_LIST_FAIL";
export const EVALUATION_RATING_LIST_RESET = "EVALUATION_RATING_LIST_RESET";

export const EVALUATION_CREATE_REQUEST = "EVALUATION_CREATE_REQUEST";
export const EVALUATION_CREATE_SUCCESS = "EVALUATION_CREATE_SUCCESS";
export const EVALUATION_CREATE_FAIL = "EVALUATION_CREATE_FAIL";

export const EVALUATION_EVALUATOR_LIST_REQUEST =
  "EVALUATION_EVALUATOR_LIST_REQUEST";
export const EVALUATION_EVALUATOR_LIST_SUCCESS =
  "EVALUATION_EVALUATOR_LIST_SUCCESS";
export const EVALUATION_EVALUATOR_LIST_FAIL = "EVALUATION_EVALUATOR_LIST_FAIL";
export const EVALUATION_EVALUATOR_LIST_RESET =
  "EVALUATION_EVALUATOR_LIST_RESET";

export const EVALUATION_LIST_REQUEST = "EVALUATION_LIST_REQUEST";
export const EVALUATION_LIST_SUCCESS = "EVALUATION_LIST_SUCCESS";
export const EVALUATION_LIST_FAIL = "EVALUATION_LIST_FAIL";
export const EVALUATION_LIST_RESET = "EVALUATION_LIST_RESET";

export const EVALUATION_USER_LIST_REQUEST = "EVALUATION_USER_LIST_REQUEST";
export const EVALUATION_USER_LIST_SUCCESS = "EVALUATION_USER_LIST_SUCCESS";
export const EVALUATION_USER_LIST_FAIL = "EVALUATION_USER_LIST_FAIL";
export const EVALUATION_USER_LIST_RESET = "EVALUATION_USER_LIST_RESET";

export const EVALUATION_RATINGS_REQUEST = "EVALUATION_RATINGS_REQUEST";
export const EVALUATION_RATINGS_SUCCESS = "EVALUATION_RATINGS_SUCCESS";
export const EVALUATION_RATINGS_FAIL = "EVALUATION_RATINGS_FAIL";
export const EVALUATION_RATINGS_RESET = "EVALUATION_RATINGS_RESET";
