export const LEAVE_CREATE_REQUEST = "LEAVE_CREATE_REQUEST";
export const LEAVE_CREATE_SUCCESS = "LEAVE_CREATE_SUCCESS";
export const LEAVE_CREATE_FAIL = "LEAVE_CREATE_FAIL";
export const LEAVE_CREATE_RESET = "LEAVE_CREATE_RESET";

export const LEAVE_USER_LIST_REQUEST = "LEAVE_USER_LIST_REQUEST";
export const LEAVE_USER_LIST_SUCCESS = "LEAVE_USER_LIST_SUCCESS";
export const LEAVE_USER_LIST_FAIL = "LEAVE_USER_LIST_FAIL";
export const LEAVE_USER_LIST_RESET = "LEAVE_USER_LIST_RESET";

export const LEAVE_LIST_REQUEST = "LEAVE_LIST_REQUEST";
export const LEAVE_LIST_SUCCESS = "LEAVE_LIST_SUCCESS";
export const LEAVE_LIST_FAIL = "LEAVE_LIST_FAIL";
export const LEAVE_LIST_RESET = "LEAVE_LIST_RESET";
